package com.pass.android.vault

import com.pass.android.net.ChangePage
import com.pass.android.net.Device
import com.pass.android.net.GetKeyBundleOutcome
import com.pass.android.net.HttpError
import com.pass.android.net.ItemRecord
import com.pass.android.net.KeyBundle
import com.pass.android.net.OpaqueStepOutcome
import com.pass.android.net.Session
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.jsonPrimitive
import kotlinx.serialization.json.long
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Test
import uniffi.crypto_ffi.ItemSession
import kotlin.random.Random

/** D02-MVP: `VaultManager` unlock-choreography and D5 lifecycle unit tests,
 * against a `FakeVaultApi`/`FakeOpaqueClient` (no network, no real OPAQUE
 * server) plus the real crypto-ffi (JNA-loaded from the host build — see
 * `app/build.gradle.kts`'s `jna.library.path` test wiring) for the actual
 * key-bundle-unlock step, using the fixture generated by
 * `crates/crypto-ffi/examples/gen_test_bundle.rs`
 * (`src/test/resources/fixtures/account-bundle-fixture.json`). The real,
 * end-to-end OPAQUE-login-against-a-real-backend path is covered
 * separately by the real-backend integration suite; this file exercises
 * everything else in the flow: fail-closed device enrollment/key-bundle
 * handling, and D5's fresh-check/lock-on-failure behavior.
 */
class VaultManagerTest {
    private data class Fixture(
        val password: String,
        val accountId: String,
        val vaultId: String,
        val itemId: String,
        val keyBundleWire: String,
    )

    private fun loadFixture(): Fixture {
        val text = javaClass.classLoader!!.getResourceAsStream("fixtures/account-bundle-fixture.json")!!
            .bufferedReader().readText()
        val obj = Json.parseToJsonElement(text).jsonObject()
        val bytes = com.pass.android.codec.AccountBundleBytes(
            accountId = obj["accountId"]!!.jsonPrimitive.content,
            vaultId = obj["vaultId"]!!.jsonPrimitive.content,
            itemId = obj["itemId"]!!.jsonPrimitive.content,
            kdfParametersCbor = com.pass.android.codec.decodeB64(obj["kdfParametersCbor"]!!.jsonPrimitive.content),
            wrappedAccountKey = com.pass.android.codec.decodeB64(obj["wrappedAccountKey"]!!.jsonPrimitive.content),
            wrappedVaultKey = com.pass.android.codec.decodeB64(obj["wrappedVaultKey"]!!.jsonPrimitive.content),
            wrappedItemKey = com.pass.android.codec.decodeB64(obj["wrappedItemKey"]!!.jsonPrimitive.content),
            wrappedRecoveryKey = com.pass.android.codec.decodeB64(obj["wrappedRecoveryKey"]!!.jsonPrimitive.content),
        )
        val wire = com.pass.android.codec.buildAccountBundle(bytes)
        return Fixture(
            password = obj["password"]!!.jsonPrimitive.content,
            accountId = bytes.accountId,
            vaultId = bytes.vaultId,
            itemId = bytes.itemId,
            keyBundleWire = wire,
        )
    }

    private fun kotlinx.serialization.json.JsonElement.jsonObject() = this as kotlinx.serialization.json.JsonObject

    private fun readyLoginResponses(): MutableList<OpaqueStepOutcome> = mutableListOf(
        OpaqueStepOutcome.MessageLeg("b64:AQ=="),
        OpaqueStepOutcome.SessionLeg(Session("access-token-1", "2999-01-01T00:00:00Z")),
    )

    @Test
    fun `unlock succeeds against an empty vault with real crypto-ffi`() {
        val fixture = loadFixture()
        val api = FakeVaultApi().apply {
            loginStepResponses = readyLoginResponses()
            getKeyBundleResult = { GetKeyBundleOutcome(200, KeyBundle(fixture.keyBundleWire, 1)) }
            listChangesResult = { throw HttpError(404, null) } // brand-new vault
        }
        val manager = VaultManager(deviceName = "test-device", createOpaqueClient = { FakeOpaqueClient() }, createApi = { api })

        val result = manager.unlock(fixture.accountId, "https://api.example.test", fixture.password.toByteArray())

        assertTrue(result is UnlockResult.Ok)
        assertTrue(manager.isUnlocked())
        assertEquals(emptyList<ItemSummary>(), manager.listItems())
    }

    @Test
    fun `unlock fails closed when the account id in the bundle does not match`() {
        val fixture = loadFixture()
        val api = FakeVaultApi().apply {
            loginStepResponses = readyLoginResponses()
            getKeyBundleResult = { GetKeyBundleOutcome(200, KeyBundle(fixture.keyBundleWire, 1)) }
        }
        val manager = VaultManager(deviceName = "test-device", createOpaqueClient = { FakeOpaqueClient() }, createApi = { api })

        val result = manager.unlock("someone-else", "https://api.example.test", fixture.password.toByteArray())

        assertTrue(result is UnlockResult.Failed)
        assertFalse(manager.isUnlocked())
    }

    @Test
    fun `unlock fails closed when device enrollment fails`() {
        val fixture = loadFixture()
        val api = FakeVaultApi().apply {
            loginStepResponses = readyLoginResponses()
            registerBearerSessionDeviceResult = { throw HttpError(400, null) }
        }
        val manager = VaultManager(deviceName = "test-device", createOpaqueClient = { FakeOpaqueClient() }, createApi = { api })

        val result = manager.unlock(fixture.accountId, "https://api.example.test", fixture.password.toByteArray())

        assertTrue(result is UnlockResult.Failed)
        assertFalse(manager.isUnlocked())
    }

    @Test
    fun `unlock fails closed when the account has never published a key bundle`() {
        val fixture = loadFixture()
        val api = FakeVaultApi().apply {
            loginStepResponses = readyLoginResponses()
            getKeyBundleResult = { GetKeyBundleOutcome(404) }
        }
        val manager = VaultManager(deviceName = "test-device", createOpaqueClient = { FakeOpaqueClient() }, createApi = { api })

        val result = manager.unlock(fixture.accountId, "https://api.example.test", fixture.password.toByteArray())

        assertTrue(result is UnlockResult.Failed)
        assertFalse(manager.isUnlocked())
    }

    @Test
    fun `unlock rejects a non-HTTPS origin before ever calling the network`() {
        val api = FakeVaultApi()
        val manager = VaultManager(deviceName = "test-device", createOpaqueClient = { FakeOpaqueClient() }, createApi = { api })

        val result = manager.unlock("acct", "http://api.example.test", "pw".toByteArray())

        assertTrue(result is UnlockResult.Failed)
        assertEquals(0, api.listDevicesCallCount)
    }

    @Test
    fun `unlock zeroizes the password buffer before returning`() {
        val api = FakeVaultApi().apply { loginStepResponses = mutableListOf(OpaqueStepOutcome.MessageLeg("b64:AQ==")) }
        // clientLoginFinish will be called with whatever's left in the
        // buffer at that point (still the real password); the buffer must
        // be zero *after* unlock() returns, regardless of outcome.
        val password = "hunter2".toByteArray()
        val manager = VaultManager(deviceName = "test-device", createOpaqueClient = { FakeOpaqueClient() }, createApi = { api })
        manager.unlock("acct", "https://api.example.test", password)
        assertTrue(password.all { it == 0.toByte() })
    }

    private fun installFakeUnlockedState(manager: VaultManager, api: FakeVaultApi) {
        manager.installUnlockedStateForTesting(
            api = api,
            session = ItemSession.create(),
            accountId = "acct-1",
            vaultId = "vault-1",
            accessTokenExpiresAt = "2999-01-01T00:00:00Z",
        )
    }

    @Test
    fun `checkFresh reuses a fresh check within the 30s window without calling the API`() {
        val api = FakeVaultApi()
        var clock = 0L
        val manager = VaultManager(deviceName = "d", now = { clock }, createApi = { api })
        installFakeUnlockedState(manager, api)

        assertTrue(manager.checkFresh()) // first call: past-due (lastFreshCheckAt=0), calls listDevices
        assertEquals(1, api.listDevicesCallCount)

        clock += 10_000 // well within the 30s window
        assertTrue(manager.checkFresh())
        assertEquals(1, api.listDevicesCallCount) // not called again
    }

    @Test
    fun `checkFresh calls the API again once the 30s window has elapsed`() {
        val api = FakeVaultApi()
        var clock = 0L
        val manager = VaultManager(deviceName = "d", now = { clock }, createApi = { api })
        installFakeUnlockedState(manager, api)

        assertTrue(manager.checkFresh())
        clock += FRESH_CHECK_INTERVAL_MS + 1
        assertTrue(manager.checkFresh())
        assertEquals(2, api.listDevicesCallCount)
    }

    @Test
    fun `checkFresh locks and reports auth failure when the fresh check gets a 401`() {
        val api = FakeVaultApi().apply { listDevicesResult = { httpUnauthorized() } }
        var authFailures = 0
        val manager = VaultManager(deviceName = "d", now = { 0L }, createApi = { api }, onAuthFailure = { authFailures += 1 })
        installFakeUnlockedState(manager, api)

        val fresh = manager.checkFresh()

        assertFalse(fresh)
        assertFalse(manager.isUnlocked())
        assertEquals(1, authFailures)
    }

    @Test
    fun `checkFresh locks on a network failure with no offline fallback`() {
        val api = FakeVaultApi().apply { listDevicesResult = { throw RuntimeException("offline") } }
        val manager = VaultManager(deviceName = "d", now = { 0L }, createApi = { api })
        installFakeUnlockedState(manager, api)

        assertFalse(manager.checkFresh())
        assertFalse(manager.isUnlocked())
    }

    @Test
    fun `lock clears state without any network call`() {
        val api = FakeVaultApi()
        val manager = VaultManager(deviceName = "d", createApi = { api })
        installFakeUnlockedState(manager, api)

        manager.lock()

        assertFalse(manager.isUnlocked())
        assertEquals(0, api.listDevicesCallCount)
        assertEquals(0, api.refreshCallCount)
        assertEquals(0, api.logoutCallCount)
    }

    @Test
    fun `logout clears local state and calls the server`() {
        val api = FakeVaultApi()
        val manager = VaultManager(deviceName = "d", createApi = { api })
        installFakeUnlockedState(manager, api)

        manager.logout()

        assertFalse(manager.isUnlocked())
        assertEquals(1, api.logoutCallCount)
    }

    @Test
    fun `saveItem rejects invalid input without touching the network`() {
        val api = FakeVaultApi()
        val manager = VaultManager(deviceName = "d", now = { 0L }, createApi = { api })
        installFakeUnlockedState(manager, api)

        val result = manager.saveItem(VaultManager.SaveItemInput(type = "login", title = ""))

        assertTrue(result is SaveItemResult.Failed)
        assertEquals(0, api.listDevicesCallCount)
    }

    @Test
    fun `saveItem seals, mutates, and updates the local item cache`() {
        val api = FakeVaultApi()
        val manager = VaultManager(deviceName = "d", now = { 0L }, createApi = { api })
        installFakeUnlockedState(manager, api)

        val result = manager.saveItem(VaultManager.SaveItemInput(type = "login", title = "Example", username = "alice", password = "s3cret"))

        assertTrue(result is SaveItemResult.Ok)
        val itemId = (result as SaveItemResult.Ok).itemId
        assertEquals(1, manager.listItems().size)
        assertEquals("Example", manager.listItems().first { it.itemId == itemId }.title)
    }

    @Test
    fun `saveItem fails locked when the vault is not unlocked`() {
        val manager = VaultManager(deviceName = "d")
        val result = manager.saveItem(VaultManager.SaveItemInput(type = "note", title = "x"))
        assertTrue(result is SaveItemResult.Failed)
        assertEquals("locked", (result as SaveItemResult.Failed).reason)
    }

    @Test
    fun `getTotp computes a code for a totp-login item and null for anything else`() {
        val api = FakeVaultApi()
        val manager = VaultManager(deviceName = "d", now = { 59_000L }, createApi = { api })
        installFakeUnlockedState(manager, api)
        manager.saveItem(
            VaultManager.SaveItemInput(type = "totp-login", title = "GitHub", username = "alice", totpSecret = "GEZDGNBVGY3TQOJQGEZDGNBVGY3TQOJQ"),
        )
        val itemId = manager.listItems().first().itemId

        val totp = manager.getTotp(itemId)

        assertEquals(true, totp?.code?.matches(Regex("^\\d{6}$")))
        assertNull(manager.getTotp("no-such-item"))
    }
}
